// Auto-generated by embedded-nn-codegen for STM32N6 TinyML deployment.
// Zero-allocation no_std neural network inference pipeline.

use embedded_nn::{Activation, Dims, FcParams, PerChannelQuantParams, fully_connected_per_channel_s8};

pub const ARENA_SIZE_BYTES: usize = 36;
pub const FLASH_WEIGHTS_BYTES: usize = 560;

static OP0_WEIGHTS_S8: [i8; 256] = [
    -67, -35, 39, -39, 105, -60, 46, -19, -66, -127, -59, -36, -51, -26, -16, 79, -67, -22, 73, -24, -22, -127, -97,
    26, 109, -125, 69, 50, -48, -14, -66, -107, -52, -11, 6, -109, 95, -67, -109, 3, 28, -127, -42, 10, 10, 12, -12,
    -123, -118, 103, -10, 10, 4, 126, 35, 23, -54, 43, -127, 31, 31, -15, 61, 115, -57, -106, -80, -48, 76, -85, 23,
    46, -123, -33, 75, -51, -64, 26, -65, -127, -61, 53, -8, 52, 26, 20, 127, 61, -83, -1, 58, -53, 115, -43, -26, 41,
    46, 65, -35, 127, 26, 93, -15, 31, -46, 75, -9, 93, 1, -116, 40, 60, -111, 127, 98, 36, -75, 20, 60, 72, 121, -69,
    123, 33, 105, -4, -79, -46, -61, 18, 109, 52, -29, 121, -41, 52, -29, 65, 3, 58, 5, 98, -127, 65, -26, -4, -113,
    20, 93, -126, 42, -98, -94, -84, 19, -93, -84, -45, -49, -127, 38, -109, 105, -89, 13, -40, 23, 10, -78, -19, 54,
    24, 88, 127, -62, 23, 24, 42, -20, -42, 10, 48, 45, 127, 51, -5, 116, -39, 101, 79, -55, -17, -127, 45, 106, 82,
    77, 78, -48, -108, 35, -15, 42, 28, -17, -110, 55, 18, -11, 114, 88, 66, -32, 61, 78, 127, 94, 51, 72, -82, -118,
    115, 75, 40, -31, -87, 59, 11, 98, 86, 90, 61, -39, 63, -127, -67, -17, 10, 8, 30, -41, 20, 118, 70, -35, 8, -67,
    127, 58, 42, 18, 88, 9, 54, -56, -25,
];

static OP0_BIAS_S32: [i32; 16] = [
    -2437, 8579, 3080, 2937, 5266, 6071, 5919, 6664, 4202, 6360, -1507, 7063, 6786, -2938, -4047, 7369,
];

static OP0_MULT_S32: [i32; 16] = [
    1443803648, 1526270464, 1814342272, 1632482048, 1692199936, 1860172928, 1638091136, 1660611456, 1291806848,
    2090611840, 1451033344, 1801734400, 1650070144, 1119260288, 1203074304, 1508238592,
];

static OP0_SHIFT_S32: [i32; 16] = [-8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8];

static OP1_WEIGHTS_S8: [i8; 64] = [
    63, 114, 20, 37, -35, -83, -79, 27, -29, -88, 21, 83, -127, 49, -2, 87, 52, -23, -87, 86, -73, 21, 127, 0, -10,
    -40, -37, -107, -11, 3, 37, 63, -37, -43, -70, -19, 112, 125, -91, -23, -127, 10, -13, 61, -72, 19, -49, -73, 86,
    95, 80, -21, 78, -126, -60, -79, -38, 26, 27, -127, -7, 40, -98, -112,
];

static OP1_BIAS_S32: [i32; 4] = [6269, -249, -37088, -28367];

static OP1_MULT_S32: [i32; 4] = [1220484864, 1255924480, 1132623104, 1136927744];

static OP1_SHIFT_S32: [i32; 4] = [-8, -8, -8, -8];

pub struct DenseMlp;

#[allow(dead_code)]
impl DenseMlp {
    pub const INPUT_DIM: usize = 16;
    pub const OUTPUT_DIM: usize = 4;
    pub const INPUT_SCALE: f32 = 0.007843138f32;
    pub const INPUT_ZERO_POINT: i32 = -1;
    pub const OUTPUT_SCALE: f32 = 0.032559004f32;
    pub const OUTPUT_ZERO_POINT: i32 = 5;
    pub const ARENA_SIZE: usize = ARENA_SIZE_BYTES;
    pub const FLASH_WEIGHTS: usize = FLASH_WEIGHTS_BYTES;

    /// Runs zero-allocation int8 inference on the Cortex-M55 CPU.
    ///
    /// The inner dot products execute via `embedded_nn::simd::vec_dot_s8`, which uses
    /// Arm Helium (MVE) vector instructions when compiled with `+mve`.
    pub fn predict<'a>(input: &[i8], arena: &'a mut [u8; ARENA_SIZE_BYTES]) -> Result<&'a [i8], &'static str> {
        if input.len() != 16 {
            return Err("Invalid input length");
        }

        let input_slice = unsafe { core::slice::from_raw_parts_mut(arena.as_mut_ptr().add(16) as *mut i8, 16) };
        input_slice.copy_from_slice(&input[0..16]);

        // Layer 0: FullyConnected 16 -> 16 + ReLU
        let in_buf = unsafe { core::slice::from_raw_parts(arena.as_ptr().add(16) as *const i8, 16) };
        let out_buf = unsafe { core::slice::from_raw_parts_mut(arena.as_mut_ptr().add(0) as *mut i8, 16) };
        let fc_params = FcParams {
            input_offset: 0,
            filter_offset: 0,
            output_offset: -128,
            activation: Activation::new(-128, i8::MAX as i32),
        };
        let quant_params = PerChannelQuantParams::new(&OP0_MULT_S32, &OP0_SHIFT_S32);
        fully_connected_per_channel_s8(
            &fc_params,
            &quant_params,
            &Dims::new(1, 1, 1, 16),
            in_buf,
            &Dims::new(16, 1, 1, 16),
            &OP0_WEIGHTS_S8,
            Some(&OP0_BIAS_S32),
            &Dims::new(1, 1, 1, 16),
            out_buf,
        )
        .map_err(|_| "FC per-channel s8 execution failed")?;

        // Layer 1: FullyConnected 16 -> 4 (Linear output logits)
        let in_buf = unsafe { core::slice::from_raw_parts(arena.as_ptr().add(0) as *const i8, 16) };
        let out_buf = unsafe { core::slice::from_raw_parts_mut(arena.as_mut_ptr().add(32) as *mut i8, 4) };
        let fc_params = FcParams {
            input_offset: 0,
            filter_offset: 0,
            output_offset: 5,
            activation: Activation::int8_unconstrained(),
        };
        let quant_params = PerChannelQuantParams::new(&OP1_MULT_S32, &OP1_SHIFT_S32);
        fully_connected_per_channel_s8(
            &fc_params,
            &quant_params,
            &Dims::new(1, 1, 1, 16),
            in_buf,
            &Dims::new(16, 1, 1, 4),
            &OP1_WEIGHTS_S8,
            Some(&OP1_BIAS_S32),
            &Dims::new(1, 1, 1, 4),
            out_buf,
        )
        .map_err(|_| "FC per-channel s8 execution failed")?;

        let result = unsafe { core::slice::from_raw_parts(arena.as_ptr().add(32) as *const i8, 4) };
        Ok(result)
    }
}

pub type ActiveModel = DenseMlp;

#[derive(Clone, Copy, Debug)]
pub struct GoldenVector {
    pub input: [i8; 16],
    pub expected_logits: [i8; 4],
    pub expected_class: usize,
}

/// Official test vectors with TensorFlow Lite golden oracle outputs.
pub static GOLDEN_TEST_VECTORS: [GoldenVector; 6] = [
    GoldenVector {
        input: [-2, 24, 24, 21, -19, 44, -33, 90, 100, -40, 53, -38, 21, 97, -128, -94],
        expected_logits: [95, -48, -25, -52],
        expected_class: 0,
    },
    GoldenVector {
        input: [-95, 71, 51, 97, 116, 58, 8, 98, -73, 54, -82, 67, 47, -15, -46, 97],
        expected_logits: [-35, 102, -64, -109],
        expected_class: 1,
    },
    GoldenVector {
        input: [-14, -1, -128, 17, 46, 53, 122, 20, -20, 1, 56, -128, 60, 53, -128, -79],
        expected_logits: [-37, -67, 93, -54],
        expected_class: 2,
    },
    GoldenVector {
        input: [
            -58, -14, -38, -43, 126, -108, -25, -76, 21, -104, -18, -99, -76, -96, 47, -40,
        ],
        expected_logits: [-32, -66, -16, 107],
        expected_class: 3,
    },
    GoldenVector {
        input: [-6, 55, 9, 28, -6, 31, -7, 71, 79, -20, 78, 23, 77, 126, -128, -78],
        expected_logits: [88, -45, -17, -83],
        expected_class: 0,
    },
    GoldenVector {
        input: [
            -104, 80, 116, 91, 126, 82, -27, 96, -50, 34, -100, 103, -44, -27, -55, 96,
        ],
        expected_logits: [-33, 112, -103, -94],
        expected_class: 1,
    },
];

/// ST Edge AI compatible Epoch Controller binary container compiled by `embedded-nn-aton`.
/// Contains complete ATON microcode instructions, streaming engine setups, and relocations for `_in` and `_out`.
pub static EC_CONTAINER: [u64; 30] = [
    0x00000014ecbf0050,
    0x0000000000000000,
    0x0000000200000048,
    0x000000010000001c,
    0x0000002400000020,
    0x0000002c00000001,
    0x0000000f006e695f,
    0x0000000074756f5f,
    0x000000000000001b,
    0x00000028ca057a7a,
    0x0000000110000000,
    0xffffffff10020000,
    0x07ffffff10040000,
    0x0001001014030000,
    0x0000000114040000,
    0x0000001014050000,
    0x0000000014090000,
    0x0000000014020000,
    0x0000800114000000,
    0x0001000410030000,
    0x0000000110040000,
    0x0000000410050000,
    0x0008000010090000,
    0x0000000010020000,
    0x0000800110000000,
    0x0000000110000000,
    0x00000001100c0000,
    0x0000001510050000,
    0x0008000040000000,
    0xf000000050000000,
];
